FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN apt-get update && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Correção no comando CMD para iniciar o Flask corretamente
CMD ["flask", "run", "--host=0.0.0.0"]
